[project]
name = "low-rank-rnn"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.22.9",
    "ipykernel>=7.3.0",
    "jaxtyping>=0.3.11",
    "matplotlib>=3.11.0",
    "numpy>=2.5.0",
    "scipy>=1.18.0",
    "torch>=2.12.1",
]

[dependency-groups]
dev = [
    "trickle-observe>=0.2.71",
]
